apiVersion: v1
kind: Namespace
metadata:
  name: tiller-world

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: tiller-world

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: tiller-world

# ---
# kind: Role
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: tiller-manager
#   namespace: tiller-world
# rules:
# - apiGroups: ["", "batch", "extensions", "apps"]
#   resources: ["*"]
#   verbs: ["*"]

# ---
# kind: RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: tiller-binding
#   namespace: tiller-world
# subjects:
# - kind: ServiceAccount
#   name: tiller
#   namespace: tiller-world
# roleRef:
#   kind: Role
#   name: tiller-manager
#   apiGroup: rbac.authorization.k8s.io
