---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: postgresql-db
  namespace: lucas
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: postgresql-db
  chart:
    git: git@github.com:helm/charts
    path: stable/postgresql
    ref: master
  values:
    postgresqlDatabase: postgresqldb
    metrics:
      enable: true
