# --- GLOBAL CONFIG --- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: lucassimpson
  namespace: lucas
  labels:
    app: lucassimpson
data:
  ENV: KUBE
  DEBUG: ISTRUE


# --- GLOBAL SECRET --- 
---
apiVersion: v1
kind: Secret
metadata:
  name: lucassimpson-dockerlogin
  namespace: lucas
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJIVmpZWE56YVcxd2MyOXVaRzlqYTJWeU9qVlVPV2c1YzJWMGNGTm1ORlJEU3c9PSIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTguMDkuNSAobGludXgpIgoJfQp9
type: kubernetes.io/dockerconfigjson


# --- WEB --- 
---
apiVersion: v1
kind: Service

metadata:
  name: lucassimpson-web
  namespace: lucas
  labels:
    app: lucassimpson-web

spec:
  type: ClusterIP
  selector:
    app: lucassimpson-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucassimpson-web
  namespace: lucas
  labels:
    app: lucassimpson-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lucassimpson-web
  template:
    metadata:
      labels:
        app: lucassimpson-web
    spec:
      containers:
      - name: lucassimpson-web
        image: lucassimpsondocker/main:lucassimpson-0.0.19
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: lucassimpson
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      imagePullSecrets:
      - name: lucassimpson-dockerlogin

# --- CELERY --- 
---
apiVersion: v1
kind: Service

metadata:
  name: lucassimpson-celery
  namespace: lucas
  labels:
    app: lucassimpson-celery

spec:
  type: ClusterIP
  selector:
    app: lucassimpson-celery
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucassimpson-celery
  namespace: lucas
  labels:
    app: lucassimpson-celery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lucassimpson-celery
  template:
    metadata:
      labels:
        app: lucassimpson-celery
    spec:
      containers:
      - name: lucassimpson-celery
        image: lucassimpsondocker/main:lucassimpson-0.0.19
        command: ["celery"]
        args: [
          "-A", "celery_config", "worker", "--loglevel=info", "--concurrency=2", "-E", "-B"
        ]
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: lucassimpson
        resources:
          requests:
            memory: "256Mi"
            cpu: "400m"
          limits:
            memory: "512Mi"
            cpu: "400m"
      imagePullSecrets:
      - name: lucassimpson-dockerlogin


# --- PRICES INJESTION --- 
---
apiVersion: v1
kind: Service

metadata:
  name: lucassimpson-prices
  namespace: lucas
  labels:
    app: lucassimpson-prices

spec:
  type: ClusterIP
  selector:
    app: lucassimpson-prices
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucassimpson-prices
  namespace: lucas
  labels:
    app: lucassimpson-prices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lucassimpson-prices
  template:
    metadata:
      labels:
        app: lucassimpson-prices
    spec:
      containers:
      - name: lucassimpson-prices
        image: lucassimpsondocker/main:lucassimpson-0.0.19
        command: ["python"]
        args: [
          "manage.py", "monitor"
        ]
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: lucassimpson
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      imagePullSecrets:
      - name: lucassimpson-dockerlogin


# --- ORDER BOOK INJESTION --- 
---
apiVersion: v1
kind: Service

metadata:
  name: lucassimpson-order-book
  namespace: lucas
  labels:
    app: lucassimpson-order-book

spec:
  type: ClusterIP
  selector:
    app: lucassimpson-order-book
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucassimpson-order-book
  namespace: lucas
  labels:
    app: lucassimpson-order-book
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lucassimpson-order-book
  template:
    metadata:
      labels:
        app: lucassimpson-order-book
    spec:
      containers:
      - name: lucassimpson-order-book
        image: lucassimpsondocker/main:lucassimpson-0.0.19
        command: ["python"]
        args: [
          "manage.py", "m_order_book"
        ]
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: lucassimpson
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      imagePullSecrets:
      - name: lucassimpson-dockerlogin



# --- FLOWER --- 
---
apiVersion: v1
kind: Service

metadata:
  name: lucassimpson-flower
  namespace: lucas
  labels:
    app: lucassimpson-flower

spec:
  type: ClusterIP
  selector:
    app: lucassimpson-flower
  ports:
  - protocol: TCP
    port: 80
    targetPort: 13337

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucassimpson-flower
  namespace: lucas
  labels:
    app: lucassimpson-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lucassimpson-flower
  template:
    metadata:
      labels:
        app: lucassimpson-flower
    spec:
      containers:
      - name: lucassimpson-flower
        image: lucassimpsondocker/main:lucassimpson-0.0.19
        command: ["celery"]
        args: [
          "-A", "celery_config", "flower", "--port=13337", "--basic_auth=lucas:hodlbois420", "--inspect_timeout=50000"
        ]
        ports:
        - containerPort: 13337
        envFrom:
        - configMapRef:
            name: lucassimpson
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      imagePullSecrets:
      - name: lucassimpson-dockerlogin


# --- INGRESS --- 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lucassimpson-ingress
  namespace: lucas
spec:
  rules:
  - host: web.lucassimpson.com
    http:
      paths:
      - path: /
        backend:
          serviceName: lucassimpson-web
          servicePort: 80
  - host: flower.lucassimpson.com
    http:
      paths:
      - path: /
        backend:
          serviceName: lucassimpson-flower
          servicePort: 80
