apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: lucas
spec:
  rules:
  - host: kube.lucassimpson.com
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-server
          servicePort: 80

