---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: lucas
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: prometheus
  chart:
    git: git@github.com:helm/charts
    path: stable/prometheus
    ref: master
